name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    env:
      CI: true
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Install CodeCov
      working-directory: src
      run: dotnet tool install --global Codecov.Tool
      
    - name: Restore dependencies
      working-directory: src
      run: dotnet restore
      
    - name: Build
      working-directory: src/
      run: dotnet build -c Debug
      
    - name: Test
      working-directory: src/
      run: dotnet test -c Debug /p:AltCoverForce=true /p:AltCover=true /p:AltCoverAttributeFilter=ExcludeFromCodeCoverage -f net6.0
      
    - name: Upload
      working-directory: src/UnitTests
      run: codecov -f coverage.net6.0.xml
