# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      working-directory: src
      run: dotnet restore
      
    - name: Build
      working-directory: src
      run: dotnet build -c Release --no-restore
      
    - name: Generate Test Code
      working-directory: src/Tests
      run: |
        dotnet ../Mixable.Tool/bin/Release/net6.0/Mixable.Tool.dll TestSchemas/Base.mxml
        dotnet ../Mixable.Tool/bin/Release/net6.0/Mixable.Tool.dll TestSchemas/Derived2.mxml
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest defusedxml
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Test
      working-directory: src/Tests/Python
      run: python3 testharness.py
